[package]
name = "engine"
version = "0.0.1"
authors = ["opendevleague"]
edition = "2018"

[dependencies]
legion = { version = "0.2.1", default-features = false }
tracing-subscriber = "0.2"
glam = "0.9.2"