[package]
name = "bunkernz_server"
version = "0.0.1"
authors = ["opendevleague"]
edition = "2018"

[[bin]]
name = "bunkernz_server"
path = "src/main.rs"

[dependencies]
engine = { path = "../engine", version = "^0" }